version: '3.8'
services:
    baguette:
        build: .
        environment:
            PATH: /home/baguette/.local/bin:$PATH
            BAGUETTE_DATABASE_URL: postgresql://baguette:baguette@db:5432/baguette
            BAGUETTE_REDIS_HOST: redis
            BAGUETTE_WEB_HOST: "0.0.0.0"
        volumes:
            - ./scripts/automigration.sh:/home/baguette/automigration.sh
            - ./baguette_bi:/home/baguette/baguette_bi
        ports:
            - 8000:8000
        depends_on: [db, redis]
    redis:
        image: redis
    db:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_DB: baguette
            POSTGRES_USER: baguette
            POSTGRES_PASSWORD: baguette
