version: '3.8'
services:
    baguette:
        build: .
        environment:
            PATH: /home/baguette/.local/bin:$PATH
            BAGUETTE_DATABASE_URL: postgresql://baguette:baguette@db:5432/baguette
        volumes:
            - ./scripts/automigration.sh:/home/baguette/automigration.sh
            - ./baguette_bi:/home/baguette/baguette_bi
        depends_on: [db]
    db:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_DB: baguette
            POSTGRES_USER: baguette
            POSTGRES_PASSWORD: baguette
